### ISSUE TITLE
hierBAPS doesn't appear to run in parallel? 

### ISSUE THREAD

**Issue by apredeus** [gtonkinhill/rhierbaps#10]
Hello Gerry, 

I'm running rhierbaps on a cluster (it's a bigger alignment, with 3k sequences and ~ 60k polymorphic sites). It seems to be running OK, but it seems to only be using 1 CPU despite the command looking like this: 

`hb.results <- hierBAPS(snp.matrix, max.depth = 2, n.pops = 20, n.cores = 64)`

Any ideas why this is? Thank you in advance.

**Comment by gtonkinhill** [comment]
Hi,

For a data set that size I'd recommend running [fastbaps](https://github.com/gtonkinhill/fastbaps). The "baps" prior  in '`fastbaps` tends to give similar results to hierBAPS.

In your case it might be currently in one of the single threaded stages of the algorithm as it can run for quite a long time on large datasets.

**Comment by apredeus** [comment]
Yes, the job ended up taking about 12h, which I don't think would have been possible on a single core - so it must have ran in parallel eventually. (Sorry, I have no idea how to properly check if it ran on multiple cores in R/Rscript). 

Thank you for your help & suggestions!
