### ISSUE TITLE
memory allocation problem

### ISSUE THREAD

**Issue by furqan915** [gtonkinhill/rhierbaps#11]
Hi,
I have used rhierbaps previously on 27 genomes' core alignment and it worked fine. But now I am working on 557 genomes's core alignment (file size = 1.6 gb). I have used this command and following message shows up:
```
> snp.matrix <- load_fasta("./clean.full.aln")
Error: cannot allocate vector of size 11.7 Gb
```
Is it issue with my system or the package?
My Linux PC has 4 cores and 8gb.
Thanks

**Comment by gtonkinhill** [comment]
Hi,

`rhierbaps` is not particularly efficient so it looks like you have run out of memory on your system.
I would recommend having a look at [fastbaps](https://github.com/gtonkinhill/fastbaps). This was designed to work with larger datasets and should speed things up quite a bit.

You could also consider using [snp-sites](https://github.com/sanger-pathogens/snp-sites) to reduce the alignment to just variable columns before passing the reduced alignment to either `rhierbaps` or `fastbaps`
