### ISSUE TITLE
Error getting assignment probabilities

### ISSUE THREAD

**Issue by andrew-hipp** [gtonkinhill/rhierbaps#13]
I have a snp dataset that is working fine in rhierbaps, except when I set `assignment.probs = TRUE`. Then, I invariable receive this error:

Error in cluster.allele.freqs[cbind(seq, 1:ncol(cluster.allele.freqs))] :
  subscript out of bounds

Is this a known issue? Is there a work-around? 
thank you.

**Comment by gtonkinhill** [comment]
Hi,

I'm having trouble reproducing this. Would it be possible to send me a small test case that reproduces the issue?
