### ISSUE TITLE
patch work

### ISSUE THREAD

**Issue by Chauncy-Fang** [gtonkinhill/rhierbaps#14]
Hello! I want to make a  patch work with rhierbaps, but I cannot find the function. Can you tell me how to make a patchwork?

**Comment by gtonkinhill** [comment]
Hi,

It might be easiest to take a look at the documentation for [patchwork](https://patchwork.data-imaginist.com/)

**Comment by Chauncy-Fang** [comment]
已收到，谢谢！Email receiving!Thanks!
