### ISSUE TITLE
Error in load alignment file.

### ISSUE THREAD

**Issue by sekhwal** [gtonkinhill/rhierbaps#16]
Hi, I am trying to make a hierarchical cluster of a total 245 bacterial samples. I ran Snippy and got a core.aln file. If I provide the .aln file as input in the rhierbaps method, it does not recognize the alignment format. Please suggest, how to an alignment file for supporting to hierbaps. 

fasta.file.name <- system.file("extdata", "seqs.fa", package = "rhierbaps") snp.matrix <- load_fasta(fasta.file.name)

error: Error in load_fasta(fasta.file.name) : Invalid msa or the file does not exist!

**Comment by sekhwal** [comment]
Hi,
I am able to upload the .aln file generated from roary and generated phylogeentic tree. Next, I am wondering if I can annotate the tree by adding locations and sources on it. Please advise if I can use rhierbaps for it.

**Comment by gtonkinhill** [comment]
Hi,

Rhierbaps has some guidance on how to this in the documentation. However, it is probably easier to refer directly to the [ggtree](https://guangchuangyu.github.io/software/ggtree/) docs
