### ISSUE TITLE
Big fasta input can't be done.

### ISSUE THREAD

**Issue by YaoXinZhi** [gtonkinhill/rhierbaps#18]
Hi, 

 I have a big fasta file containing 2000 sequence alignment results with11G.

When I use the "snp.matrix <- load_fasta(fasta.file.name)" command, it will run for a very long time, may a few hours, and finally, the program will be automatically killed because of "out of memory".

I'm curious if there are other ways to approach this, in the face of very large alignment fasta files (too many sequences), or is there a suggested file size for input fasta ?

**Comment by YaoXinZhi** [comment]
Additionally, my sequence alignment files are computed by generate_ska_alignment.py in gubbins（https://github.com/nickjcroucher/gubbins）.

**Comment by gtonkinhill** [comment]
Hi, I recommend using [fastbaps](https://github.com/gtonkinhill/fastbaps/). It runs substantially quicker and tends to produce better results.

**Comment by YaoXinZhi** [comment]
Hi, 
thanks a lot for your suggestion, I checked the paper of fastbaps, and it looks like this tool optimizes the "large datasets problem", I'd like to try this tool soon.
