### ISSUE TITLE
Big data loading.

### ISSUE THREAD

**Issue by YaoXinZhi** [gtonkinhill/rhierbaps#19]
Hello

When I load a large fasta file, my R reports the following error.

`
> sparse.data <- import_fasta_sparse_nt(fasta.file.name)
Error: cannot allocate vector of size 15.3 Gb
`

I think this is a generic problem that users encounter when using R, so I was just wondering if you had a good solution, especially when using fastbaps.

Thanks!

**Comment by gtonkinhill** [comment]
Hi,

It looks like your file is too large to fit in the memory of your computer. You could try loading first via `ape::read.FASTA` but this might have a similar issue.

If this doesn't work the only idea I have is to either run the analysis on a computer with more memory or subset the dataset. I hope this helps a bit.
