### ISSUE TITLE
Error when trying to plot the results

### ISSUE THREAD

**Issue by cpavloud** [gtonkinhill/rhierbaps#20]
Hello!
I am trying to use `rhierbaps` on my data. I am working with `R version 4.1.1` and 
`phytools_1.5-1   maps_3.4.0       ape_5.7          ggtree_3.2.1     rhierbaps_1.1.4`

The first issue I have is that when I try to run 
> gg <- ggtree(iqtree_Current_Katsares_16S_COI,layout="circular")
> gg <- gg%<+%hb.results_Current_Katsares_16S_COI$partition.df
> gg <- gg+geom_tippoint(aes(color=factor(`level 1`)))
> gg

I get an error

`Error: Must request at least one colour from a hue palette.`

Also, when I try to run 
> plot_sub_cluster(hb.results_Current_Katsares_16S_COI, iqtree_Current_Katsares_16S_COI, level = 1, sub.cluster = 1)

I get the error 
`Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "waiver"
In addition: Warning message:
In drop.tip.phylo(tree, tree$tip.label[!tree$tip.label %in% cluster.isolate]) :
  drop all tips of the tree: returning NULL`

Do you have any idea how to solve this?

**Comment by gtonkinhill** [comment]
Hi,

I am having trouble reproducing your issue using the latest version `rhierbaps` and `ggtree`. If you are able to send though the data to reproduce the problem I would be happy to take a closer look.

It should be sufficient to send the `hb.results_Current_Katsares_16S_COI` data.frame and the `iqtree_Current_Katsares_16S_COI` tree.

**Comment by cpavloud** [comment]
Sure!
I have attached the `hb.results_Current_Katsares_16S_COI$partition.df` file and the tree file I loaded in the script.


[hierbaps_partition_Current_Katsares_16S_COI.csv](https://github.com/gtonkinhill/rhierbaps/files/11192809/hierbaps_partition_Current_Katsares_16S_COI.csv)
[16S_COI_katsares_and_ours_100seqs_982bp.fas.treefile.txt](https://github.com/gtonkinhill/rhierbaps/files/11192824/16S_COI_katsares_and_ours_100seqs_982bp.fas.treefile.txt)

**Comment by gtonkinhill** [comment]
Hi,

It looks like the issue is caused by the names of tips in the tree being different to those passed to `rhierbaps`.

I had a look and one seems to include trailing white space. You can check this with the following commands

```
all(tree$tip.label %in% hb.results$Isolate)
tree$tip.label[!tree$tip.label %in% hb.results$Isolate]
```

This will print the missing names. To resolve the white space issue, you can use stringr as

```
hb.results$Isolate <- stringr::str_trim(hb.results$Isolate)
```

This should then work although it looks like there is still one missing label. The full set of commands I used are

```
library(rhierbaps)
library(ggtree)
library(ape)
library(tidyverse)


tree <- ape::read.tree("~/Downloads/16S_COI_katsares_and_ours_100seqs_982bp.fas.treefile.txt")
hb.results <- read_csv("~/Downloads/hierbaps_partition_Current_Katsares_16S_COI.csv")


hb.results$Isolate <- stringr::str_trim(hb.results$Isolate)

all(tree$tip.label %in% hb.results$Isolate)
tree$tip.label[!tree$tip.label %in% hb.results$Isolate]

gg <- ggtree(tree, layout="circular")
gg <- gg %<+% hb.results
gg <- gg + geom_tippoint(aes(color=factor(`level 1`)))
gg
```

**Comment by cpavloud** [comment]
Thank you for taking the time to look at this. 

I corrected the names in the hb.results by running
`hb.results$partition.df$Isolate <- stringr::str_trim(hb.results$partition.df$Isolate)
`
instead of 
`hb.results$Isolate <- stringr::str_trim(hb.results$Isolate)
`

and then I was able to plot the tree, but running 
`gg <- gg %<+% hb.results$partition.df
`
instead of 
`gg <- gg %<+% hb.results
`

However, the tree has also an "NA" factor. Is this normal?
![tree](https://github.com/gtonkinhill/rhierbaps/assets/32954293/d0a8586e-b66f-4b7e-a911-15ae0d906e32)

**Comment by gtonkinhill** [comment]
Hi,

This might be because you have an isolate in the phylogeny that is missing from the hierbaps analysis. Can you double check that the isolates in the phylogeny are the same as those passed to hierbaps?

**Comment by cpavloud** [comment]
You are right, there was one isolate that had a "/" in its name, that was converted to "_" in the tree and thus, they didn't match. 
Now it's ok!
Thank you!
