### ISSUE TITLE
Devtools installation fail. WITH SOLUTION.

### ISSUE THREAD

**Issue by andersgs** [gtonkinhill/rhierbaps#3]
Hi.

On Linux, I have experienced the following:

```
devtools::install_github("gtonkinhill/rhierbaps")

from URL https://api.github.com/repos/gtonkinhill/rhierbaps/zipball/master
Installation failed: error in running command
```

Following instructions [here](https://github.com/r-lib/devtools/issues/804) I was able to install.

Basically, do the following:

```
options(unzip = "internal") # before running this, I checked with getOption, and the unzip was unset
devtools::install_github("gtonkinhill/rhierbaps")
```

Cheers. Anders.

**Comment by gtonkinhill** [comment]
Hi Anders,

Sorry for the very delayed reply, I left your issue up as it was a problem with devtools on some operating systems and I felt that by leaving it up it might help others with the same problem. I've run into the issue myself with other packages.

I've now managed to get the package on CRAN so this problem can be avoided.

Thanks

Gerry
