### ISSUE TITLE
Issue installing/compiling RcppParallel dependency with clang 

### ISSUE THREAD

**Issue by EpiDemos82** [gtonkinhill/rhierbaps#4]
I had an issue installing most likely due to compiling with clang.  I installed RcppParallel separately via: devtools::install_github("RcppCore/RcppParallel") and it seemed to address the issue.  I am not sure how pervasive this is, but I thought it was worth sharing.

**Comment by gtonkinhill** [comment]
I left this up in case it was useful to others, but hopefully the latest update removes the dependency that relied on RcppParallel.
