### ISSUE TITLE
Problem read my multifasta

### ISSUE THREAD

**Issue by OrsonMM** [gtonkinhill/rhierbaps#5]
Dear team rhierbaps

I have problem read my multifasta. 

> library(rhierbaps)
> fasta.file.name <- system.file("extdata", "new_3_snp.fasta", package = "rhierbaps")
> fasta.file.name
[1] ""
> snp.matrix <- load_fasta(fasta.file.name)
Error in load_fasta(fasta.file.name) :
  Invalid msa or the file does not exist!

I can see that the  fasta.file.name is empty.  

I check if all if okey with the data(woodmouse) example, all run okey. 

I put a resume of my multifasta:

>FD01851321.fasta.ref
CGGACAGCTTCAAGGTTGTTGTTGCTCCCTAGTCAGAGTCTGCGCGATGGGAGTCAACAGCTGGCCTCCAACCTTTTTGC
GCTTAATTTTGTCTGGAACCAGCGGCATGGACCTCCGAATATTTCCGTACAACGACTATCTGTCGCAGGGACGGGGTGAT
CGCTCGGGTAGGCTATATCTTTGTTCTACAAACCCATCGCGAAGTCTATACATGCTGACCTTTGCTAGGTACCTCCGTCT
AGCGGCCCGCTCCGAATAGCCGGTACTTATACTAGAGTCTCGGAGGGATTAAGCGGTATGCCAAGAGAACGAGGCTGTTG
TGATATGATCAATCTTATAAAAGGTAGGAGTGACGTCTTATAGTGTGCATTGTTTCTGTCAGAATGATAGCCCTCTAGTA
AGAACAGTCCGAATCCCCGGAACGGGCGGGAAGAGACTGACGGTAAAATAAGCTGCGATCCCGCACGTATTTACTCTACA
GAGTTTTCGCTCTCGCTCCTATCCCTCCGTCCGTCCTAAGAGGATGCATGTGCGTTACTGGATGCTGTGTGTCGTCAAAA
AGCCCGAAGCGCCATTGGTCCGCTAGCGCATACGATGCGCGTATGAACGCAGCCGGTCAACTGTTCGTTTGGGCTTGGTG
AAAGACTTGGGTTTAACTGCATGGTCGAATATAAGCTATCACTAAAACCCTAGTTCCTAACGGGGAAGCGCCTTCAGGGT
GAGGGAAGACACCGTCAGAGTAGGTATCAGAGGGACAGGCAACATGGGCTCATATAGCCTTGGGCTCGACCAAGAGGCAA
GGTGCAGATCCGAGTCTAGAGATTCGGACGCATTGGCGCGGAGGTCGAGTTGGCCGCATGGGAAAATGCTACGTCAGGAA
ATGCAGCTAGGCGCACAGGCGCCAGACGAGCATATGGGGCACCATCTCGATCCCGACCCCGTGGCCAGGGCAGCTGTTGG
GGTGGGTAGCCGGCCGGGAATACGGATCGGAACCGTGGTGAAACACAGATTCTGCAGCCATCGACTTTCTTACGATGTAA
GGGGCTCAGTTTTTGCAGGCGGCGTACGGCGACGTCGCTACCTGCCCTTTGGAAACACACATACTGTGCGCGAAACCGCT
CCGGAACATGGGTCCCACCCTCACTCCCAACTTAGCGTTTGGAGCTCGTACACGTATGATACAAAATAAGGACGATCCTT
ACATCATCGGCGGAACCGTGTTACCCGTCATGCTAATTATCATGGATCTCCAATTTGTATACCAGGCAATACCGGGCAAA
AAGATCGCGAAGGGAGACTCAACACTGGCAACGGTCCCAGCCGTACGGGTTTCATATATGCAGCTCCGTTGAAACGGTCG
TTGGCTACATTCTGTAACGGCCGCGGTAGGAATCTGCGCGGTCCGCCTCCGCCGCATTTTCTGGTTATAAAATACATTGG
CTGTTGTGTATCGCCCCCGCACACCGAATTACGCGACTACTTACCATGGCTTTGGCACCGTTGGTCGGGTGTGAACCATG
GACAGGCTCGTCAGGACTATGCCGGTTGGAGTACTAAGCCTCAGCCAGTTACTGTTCTGCGTTACTAGCCGTGCGATTCA
TCTAGTCTGTCTCTCAACAACGATGGTTTTTCAGAAATATCTCCACCCAAGTCCCCGAATACGCCGGGACGTTCATCAGT
TGAGCAGTGCATAACTACCTGGAGATCTTTAAGCCCACGCATAGATGACGCTCTATCAGCATCCGGCGGACATAGACCAG
GCAACTGGAACCATGTGGTGTAAAAACAGATGCTCAAGCACACCGGGACGGCCCACACTCTTCATCGGCACCCAAGGAAA
AGCAGCTTCCCTCGGGTTTCAGGCTACTTAACTTAGGCCGGGGAACCCAGAGGTGCTATGCACTCGGGATGTTCGTCTAA
GAAATCGCAGATCCTTTGGATGGTTTGCGAACGGTGTATGCAATTTCGCCTTACAATCCATTTCGTCTAACACCAAGCCA
GCCTTCTTGTGAATGTCGTGCCAAAAGAAGAGTAGAGAATAGATGAACGCTTAGTCTCAGACCGGGAACTAGCGAGTATG
GCATTAAACGTGGTCCTGCAATTTGGACCTAGGGTGCCAATCAGACCTGTGCAACCGCCGCGACTACAGCCATTTGTTTT
TCAAAGACCACAGGTTTATCGTCCGCATAATGAGCGTGAACGCCGCGTGGCCACACACAGAAATACCGGTTTCATTTCCA
TCGAATTTGAGGTCTTTAGGCTGACGCGATGACGTGGGTCCAACGAGATTGCTGTTCGCGATATCGCTCGACAAATCGAC
GGCGAATACCGAATGGCATCTCAAGCCCCGCCCTATTTAGTACACTGGAGACGAGGCACAGCGATCCCCTGCCGCGAGGC
GCGTTAGCCGCCGCGGGTACAAGGTGAACCGCTTCAAGAAAACCTATGAGCTGCGAGCGAGAGGTCCGACCCATTAACAT
AGCACTGAGGCTCAGGAATCCAATCCCGCGCAAGACGATGTCCGATGAGCAACCTCCCAGCCTCCTGAGGGGAAGACGCC
AGTATCGGAAATACTAACCCCACAAAGATAGCCTCTTAGTTGGGTGGCCATCTTAAGTATCAAGGACGAAAAAGAGTCCG
CTAGGTTAAGCCCAAGG
>895.fasta
CAGACAGCTTCAAGGTTGTTGTTGCTCCCTAGTCAGAGTCTGCGCGATGGGAGTCAACAGCTGGCCTCCAACCTTTTTGC
GCTTAATTTTGTCTGGAACCAGCGGCATGGACTTCCGAATATTTCCGTACAACGACTATCTGTCGCAGGGACGGGGTGCT
CGCTCGGGTAGGCTATATCTTTGTTCTACAAACCCATCGCGAAGTCTATACATGCTGACCTTTGCTAGGTACCTCTGTCT
AGCGGCCCGCTCCGAATAGCCGGTACTTATACCAGAGTCTCGGAGGGATTAAGCGGTATGCCAAGAGAACGAGGCTGTTG
TGATCTGATCAATCTTATAAAAGGTAGGGGTGACGTCTTATAGTGTGCATTGTTTCTGTCAGAATGATAGCCCTCTAGTA
AGAACAGTCCGAATCCCCGGAACGGGCGGGAAGAGACTGACGGTAAAATAATCTGCGATCCCACACGTATTTACTCTACA
GAGTTTTCGCTCTCGCTCCTATCCCACCGTCCGTCCTAAGAGGACGCATGTGCGTTACTGGATGCTGTGTGTCGTCAAAA
AGCCCGAAGCGCCATTGGTCCGCTAGCGCATACGATGCGCCTACGAACGCAGCAAGTCAACCGTTCGTTTGGGCTTGGTG
AAAGACTTGGGTTTAACTGCATGGTCGAATATAAGCTATCACTAAAACCCTAGTTCCTAACGGGGAAGCGCCTTCAGGGT
GAGGGAAGACACCGTCAGAGTAGGTATCAGAGGGACAGGCAACATGGGCTCATATAGCCTTGGGCTCGACCGGGAGGCAA
GGTGCAGATCCGAGTCTAGAGATTCAGACGCATTGGCGCGGAGGTCGAGCTGGCCGCATGGGAAAATGCTACGTCAGGAG
AAGCAGCTAGGCGCACAGGCGCCAGACGAGCATATGGGGCACCATCTCGATCCCGACCCCGTGGCCAGGGCTGTTGTTGG
GGTGGGTAGCCGGCCGGGAATACGGATCGGAACCATGGTGAAACACAGATTCTGCCACCATCGACTTTCTTACGATGTAA
GGGGCTCAGTTTTTGCAGGCAGCGTACGGCGACGTCGCTACCTGCCCTTTGGAAACACACATACTGTGCGCGAAACCACT
CCGGAACATGGGTCCCACCCTCACTCCCAACTTAGCGTTTGGAGCTCGTACACGTATGATACAAAATAAGGACTATCCTC
ACATCATCGGCGGAACCGTGTTACCCGTCATGCTAATTATCATGGATCTCCAATTTGTATACCAGGCAATACCGGGCAAA
AAGACCGCGAAGGGAGACTCAACACTGGTAACGGTCCCAGCCGTACGGGTTTCATATATGCAGCTCTGTTGAAACGGTCG
TTGGCTACATTCTGTAACGTCCGCGGTAGGAATCTGCGCGGTCCGCCTCCGCCGCATTTTCTGGTCATAAGATACATTGG
CTGTTGTGTATCGCCCCCGCACACCGAATTACGCGACGACTTACCATGGCTTTGGCACCGTTGGTCGGGTGCGAACCATG
GACAGGCTCGTCAGGACTATGCCGGTTGGAGTACTAAGCCTCAGCCAGTTACTGTTCTGTGTTACTAGCCTTGCGATTCA
TCTAGTCTGTCACTCAACAACGATGGTTTTTCAGAAATATCTCCACCCAAGTCCCCGAATACGCCGGGACGTTCATCAGT
TGAGCAGTGCATAACTACCTGGAGATCTTTAAGCCCACGCATAGATGACGCTCTATCAGTATCCGGCGGACATAGACCAG
GCAACTGGAACCATGTGGTGTAAAAACAGATGCTCAAGCACACCGGGACGGCCCACACTCTTCGTCGGCACCCAGGGAAA
AGCAGCTTCCCTCGGGTTTCAGGCTACTTAACTTAGGCCGGGGAGCCCAGAGGTGCTATGCACTCGGGATGTTCGTCTAA
GAAATCGCAGATCCTTTGGATGGTTTGCGAACGGTGTATGCAATTTCGCCTTACAATCCATTTCGTCTAACAACAAGCCA
GCCTTCTTGTGAATGTCGTGCCAAAAGAAGAGTAGAGAATAGATGAACGCTTAGTCTCAGACCGAGAACTAGCGAGTATA
GCATTAAACGTGGTCCTGCAATTTGGACCTAGGGTGCCAATCATACCTGGGCAACCGCCGCGACTACAGCCATTTGTTTT
TCAAAGACCACAGGTTTATCGTCCGCATAACGAGCGTGAACGCCGCGTGGCCACACACAGAAATACCGGTTTCATTTCCA
TCGAATTTGAGGTCTTTAGGCTGACGCGATGACGTGGGTCCAACGAGATTGCTGTTCGCGATATCGCTCGACAAATCGAC
GGCGAATACCGAATGGCATCTCAAGCCCCGCCCTATTTAGTACACTGGAGACGAGGCACAGCTACCCCCTGCCGCGAGGC
GCGTTAGCCGTCGCGAGTATAAGGTGAACCGCTTCAAGAAAACCTATGAGCTGCGAGCGAGAGGTCCGACCCATTAACAT
AGCACTGGGGCTCAGGAATCCAATCCCGCGCAAGACGATGCCCGATGAGCAACCTCCCAGCCTCCTGAGGGGAAAACGCC
AGTATCGGAAATACTAACCACACAAAGATATCCTCTTAGTTGGGTGCCCATCTTAAGTATCAAGGACGAAAAAGAGTCCG
CTAGGTTAAGCCCAAGG
>and so on

Please help

**Comment by gtonkinhill** [comment]
Hi,

You have entered the file name into R incorrectly it should be

`fasta.file.name <- "new_3_snp.fasta"`

assuming your file is in your current working directory. Let me know if you still have issues.

**Comment by OrsonMM** [comment]
Dear gtonkinhill 

I can do that using Ape library 

dna <- ape::read.dna(dna_file, format="fasta")
snp.matrix <- snp.matrix <- load_fasta(fasta.file.name) 

and do on ... all run okey. 

Thank you so much for your rapid comment. 

I have other question maybe you can help me. 

What is mean the level´s in the results of rhierbaps.  Is possible chooose a optimal level using the values ML.   ?   Or each level what´s mean. 

I dont understand very well the levels. or depent of the depth of branch in my tree. 

Please.

**Comment by gtonkinhill** [comment]
The levels command allows you to investigate possible substructure in a cluster. There is no real optimal number of levels and rather it is probably best motivated by looking at the results. Generally I would look at the top 2.
