### ISSUE TITLE
plot_sub_cluster font size

### ISSUE THREAD

**Issue by msuareze** [gtonkinhill/rhierbaps#6]
Is there a way to change the tips font size in the plot_sub_cluster function? The labels are overlapping. I tried to export the plot as a vector and then to modify it with ggtree or ggplots but none worked. Thanks!

**Comment by gtonkinhill** [comment]
Hi, unfortunately it's not very easy as the ggtree zoom function doesn't allow for many changes. It's probably easiest to run the code from the function yourself which will allow you to change the attributes of the different tree. In your case you could run (adjusting the example from the vignette):

```
hb.object <- hb.results
tree <- iqtree
level <- 1
sub.cluster <- 9

level <- level+1
cluster.isolate <- hb.object$partition.df$Isolate[hb.object$partition.df[,level]==sub.cluster]

#Need to create a tempfile to supress the output of gzoom
ff <- tempfile()
grDevices::png(filename=ff)
gg2 <- ggtree::gzoom(tree, focus=which(tree$tip.label %in% cluster.isolate))
grDevices::dev.off()
unlink(ff)

temp_column_id <- paste(c("factor(`level ", level, "`)"), collapse = "")

p2 <- gg2$p2

# remove the old tip lables
gg2$p2$layers <- gg2$p2$layers[-3]
# add new ones
p2 <- p2 + ggtree::geom_tiplab(size=10)

p2 <- ggtree::`%<+%`(p2, hb.object$partition.df)
p2 <- p2 + ggtree::geom_tippoint(ggplot2::aes_string(color=temp_column_id))
p2 <- p2+ ggplot2::labs(color=temp_column_id) + ggplot2::theme(legend.position="right") 
p2

ggtree::multiplot(gg2$p1, p2, ncol = 2)
```

Here I've changed the tip size to 10, which requires you to first remove the old tip labels.

**Comment by msuareze** [comment]
Thanks! Sorry for answering until now, but I could not test it before. It worked very well, I had to use size=2, because of the number of tips.
It would be very cool too if eventually the figure could be exported as pdf or svg.
