### ISSUE TITLE
admixture plot

### ISSUE THREAD

**Issue by mattbawn** [gtonkinhill/rhierbaps#7]
Hi

Does the package have any capability to reproduce the admixture plot that can be produce in `hierBAPS` by running `./run_drawSnpMat.sh`?

Thanks,

Matt

**Comment by gtonkinhill** [comment]
Hi Matt, 

I'm afraid not. It might be possible to transform the data into the same format as required by that function or to reproduce it in R. In the future if I get time I will have a look at adding that functionality but I'm afraid that won't be for a while.

Best

Gerry

**Comment by mattbawn** [comment]
Hi Gerry,

OK, thanks for the info.

Best,

Matt
