### ISSUE TITLE
Admixture assignments

### ISSUE THREAD

**Issue by cizydorczyk** [gtonkinhill/rhierbaps#8]
Hello,

How are the cluster probabilities optionally produced by rhierBAPS related to admixture? I may be fundamentally misunderstanding something here, but do they correspond to the proportion of each isolate's genome that is thought to come from each cluster? I.e. do they correspond to what would be plotted on a STRUCTURE type bar plot?

(Different from #7 as I'm interested in the concept behind these probabilities -- not in generating a plot)

**Comment by gtonkinhill** [comment]
Apologies for not getting back you on this, it slipped through the cracks. hierBAPS does not model admixture and rather assumes that each isolate originates from a single cluster. The original BAPS software has an extension that allows for admixture analysis but this in not included in this version.
