### ISSUE TITLE
Speed-up r-hierbaps analysis

### ISSUE THREAD

**Issue by npavlovikj** [gtonkinhill/rhierbaps#9]
Hi @gtonkinhill ,

I was wondering if you have any suggestions on how to speed-up the `r-hierbaps` analysis.

I am running `r-hierbaps` on 3 datasets (output from Roary) with different sizes.
The first dataset has ~1,300 sequences. Running `r-hierbaps` on 1 node and 1 core took ~4 hours and ~130 GB of RAM. I am also using depth=1 and 150 populations.
For my second dataset with ~2,400 sequences, `r-hierbaps` ran for 11 days and consumed ~300GB of RAM.
The third dataset is significantly larger, with ~20,000 sequences. It is currently running on our cluster using 8 cores, but considering the previous running times and memory used, I am worried that it might not finish soon.

Thus, I was wondering if it is possible to run sub-parts of `r-hierbaps` in parallel and merge them afterwards, so the running time can be improved?
I know the MATLAB version of `r-hierbaps` is recommended for larger datasets, but I am having some issues with the MCR versions...

I would really appreciate any suggestions regarding this!

Thank you,
Natasha

**Comment by gtonkinhill** [comment]
Hi, we've actually been done some work to speed up the algorithm and the new method is available at https://github.com/gtonkinhill/fastbaps 

The new approach offers a number of different priors with the 'baps' prior generating results most similar to the hierbaps algorithm.

I should really add a message to make finding the new method a bit easier.

**Comment by npavlovikj** [comment]
Many thanks for the information @gtonkinhill , I will give `fastbaps` a try.
